# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/terasud/PycharmProjects/orario-marty/ui/orarioUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 340)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 61, 27))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 180, 61, 27))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 60, 201, 27))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(440, 10, 191, 27))
        self.label_4.setObjectName("label_4")
        self.startTime = QtWidgets.QTimeEdit(self.centralwidget)
        self.startTime.setGeometry(QtCore.QRect(170, 10, 118, 41))
        self.startTime.setTime(QtCore.QTime(8, 0, 0))
        self.startTime.setObjectName("startTime")
        self.endTime = QtWidgets.QTimeEdit(self.centralwidget)
        self.endTime.setEnabled(False)
        self.endTime.setGeometry(QtCore.QRect(110, 170, 118, 41))
        self.endTime.setObjectName("endTime")
        self.startBreak = QtWidgets.QTimeEdit(self.centralwidget)
        self.startBreak.setGeometry(QtCore.QRect(630, 0, 118, 41))
        self.startBreak.setTime(QtCore.QTime(12, 0, 0))
        self.startBreak.setObjectName("startBreak")
        self.durationBreak = QtWidgets.QTimeEdit(self.centralwidget)
        self.durationBreak.setGeometry(QtCore.QRect(630, 50, 118, 41))
        self.durationBreak.setTime(QtCore.QTime(0, 30, 0))
        self.durationBreak.setObjectName("durationBreak")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 230, 141, 27))
        self.label_5.setObjectName("label_5")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(200, 230, 571, 27))
        self.resultLabel.setObjectName("resultLabel")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 80, 131, 27))
        self.label_7.setObjectName("label_7")
        self.durationWork = QtWidgets.QTimeEdit(self.centralwidget)
        self.durationWork.setGeometry(QtCore.QRect(170, 70, 118, 41))
        self.durationWork.setTime(QtCore.QTime(7, 12, 0))
        self.durationWork.setObjectName("durationWork")
        self.calcola = QtWidgets.QPushButton(self.centralwidget)
        self.calcola.setGeometry(QtCore.QRect(590, 170, 122, 43))
        self.calcola.setObjectName("calcola")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 39))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calcolatore orario di lavoro"))
        self.label.setText(_translate("MainWindow", "inizio:"))
        self.label_2.setText(_translate("MainWindow", "fine:"))
        self.label_3.setText(_translate("MainWindow", "durata pausa pranzo:"))
        self.label_4.setText(_translate("MainWindow", "inizio pausa pranzo:"))
        self.label_5.setText(_translate("MainWindow", "orario calcolato:"))
        self.resultLabel.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "ore di lavoro:"))
        self.calcola.setText(_translate("MainWindow", "Calcola"))
